name: aws

on:
  push:
    branches:
      - main
    tags:
      - aws:*
    paths:
      - aws/**
  pull_request:
    paths:
      - .github/workflows/_build.yaml
      - .github/workflows/aws.yaml
      - aws/**

jobs:
  build-docker-image:
    uses: ./.github/workflows/_build.yaml
    with:
      path: aws
    secrets: inherit
