name: az

on:
  push:
    branches:
      - main
    tags:
      - az/v[0-9]+.[0-9]+.[0-9]+
    paths:
      - .github/workflows/_build.yaml
      - .github/workflows/az.yaml
      - az/**
  pull_request:
    paths:
      - .github/workflows/_build.yaml
      - .github/workflows/az.yaml
      - az/**

jobs:
  build-docker-image:
    uses: ./.github/workflows/_build.yaml
    with:
      path: az
    secrets: inherit
