name: Build Docker image

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

defaults:
  run:
    shell: pwsh

jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        shell: pwsh
        working-directory: ${{ inputs.path }}
        run: |
          Invoke-Pester -Configuration @{
             Run = @{
                 Exit = $true
             }
          }

      - name: Build
        shell: pwsh
        working-directory: ${{ inputs.path }}
        run: |
          $docker = Convert-FromJson $(docker version --format json)
          if (-not ($docker.Server.Platform.Name.StartsWith("Docker Desktop"))) {
              # Register handlers for additional architectures
              docker run --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
          }

          docker build .

