name: Build Docker image

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

defaults:
  run:
    shell: pwsh

jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test
        shell: pwsh
        working-directory: ${{ inputs.path }}
        run: |
          Install-Module Pester -Force
          Invoke-Pester -Configuration @{
             Run = @{
                 Exit = $true
             }
          }

      - name: Build
        shell: pwsh
        working-directory: ${{ inputs.path }}
        run: |
          docker build .
