name: default

on:
  push:
    tags:
      - "*:*"

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker image
        shell: pwsh
        run: |
          $registry=$("$Env:GITHUB_REPOSITORY".Split("/")[0])
          $repository=$("$Env:GITHUB_REF".Replace("refs/tags", "").Split(":")[0])
          $version=$("$Env:GITHUB_REF".Replace("refs/tags", "").Split(":")[1])

            --label org.opencontainers.image.created="$(Get-Date -Format "yyyy-MM-ddThh:mm:ssZ")" `
            --label org.opencontainers.image.source="$Env:GITHUB_SERVER_URL/$Env:GITHUB_REPOSITORY/$repository" `
            --label org.opencontainers.image.revision="$(git rev-parse HEAD)"
