name: default

on:
  push:
    tags:
      - "*/*"

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          docker run --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
          docker buildx create --use
          docker buildx inspect --bootstrap

          registry=$(echo $GITHUB_REPOSITORY | sed -En "s/^(.+)\/(.+)$/\1/p")
          repository=$(echo $GITHUB_REF | sed -En "s/^refs\/tags\/(.+)\/(.+)$/\1/p")
          tag=$(echo $GITHUB_REF | sed -En "s/^refs\/tags\/(.+)\/(.+)$/\2/p")
          pushd "$repository"

          docker buildx build . \
            --platform=linux/amd64,linux/arm64 \
            --push \
            --tag "$registry/$repository:$tag" \
            --label org.opencontainers.image.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --label org.opencontainers.image.source="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/$repository" \
            --label org.opencontainers.image.revision=$(git rev-parse HEAD)
