name: default

on:
  push:
    tags:
      - "*:*"

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker image
        shell: pwsh
        run: |
          Write-Output "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          docker run --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
          # Create a new builder instance and set it as the current instance
          # Build commands invoked after this command will run on this builder
          docker buildx create --use

          # Inpect the builder instance and information about it
          docker buildx inspect --bootstrap

          $registry=$("$Env:GITHUB_REPOSITORY".Split("/")[0])
          $repository=$("$Env:GITHUB_REF".Replace("refs/tags", "").Split(":")[0])
          $version=$("$Env:GITHUB_REF".Replace("refs/tags", "").Split(":")[1])

          Write-Output "registry: $registry, repository: $repository, version: $version"

          Push-Location "$repository"

          # Start a build
          docker buildx build . `
            --platform=linux/amd64,linux/arm64 `
            --push `
            --tag "$registry/$repository:$version" `
            --label org.opencontainers.image.created="$(Get-Date -Format "yyyy-MM-ddThh:mm:ssZ")" `
            --label org.opencontainers.image.source="$Env:GITHUB_SERVER_URL/$Env:GITHUB_REPOSITORY/$repository" `
            --label org.opencontainers.image.revision="$(git rev-parse HEAD)"
