name: pester

on:
  push:
    branches:
      - main
    tags:
      - pester/v[0-9]+.[0-9]+.[0-9]+
    paths:
      - .github/workflows/_build.yaml
      - .github/workflows/pester.yaml
      - pester/**
  pull_request:
    paths:
      - .github/workflows/_build.yaml
      - .github/workflows/pester.yaml
      - pester/**

jobs:
  build-docker-image:
    uses: ./.github/workflows/_build.yaml
    with:
      path: pester
    secrets: inherit
