name: pwsh

on:
  push:
    branches:
      - main
    tags:
      - pwsh:*
    paths:
      - pwsh/**
  pull_request:
    paths:
      - .github/workflows/build-docker-image.yaml
      - .github/workflows/pwsh.yaml
      - pwsh/**

jobs:
  build-docker-image:
    uses: ./.github/workflows/build-docker-image.yaml
    with:
      path: pwsh
    secrets: inherit
